# Generated by Django 3.2.9 on 2021-11-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('question', '0001_initial'),
        ('classroom', '0003_auto_20211105_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='modules',
            field=models.ManyToManyField(blank=True, to='module.Module'),
        ),
        migrations.AddField(
            model_name='subject',
            name='questions',
            field=models.ManyToManyField(blank=True, to='question.Question'),
        ),
    ]
