# Generated by Django 3.2.6 on 2021-10-19 05:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_tutorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='students',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
