# Generated by Django 3.2.6 on 2021-10-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tutorprofile_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
