# Generated by Django 3.2.6 on 2021-10-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bookings_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='is_active',
        ),
    ]
