# Generated by Django 3.2.6 on 2021-10-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bookings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='on_session',
            field=models.BooleanField(default=False),
        ),
    ]
