# Generated by Django 3.2.6 on 2021-10-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bookings_on_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='book_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
