# Generated by Django 3.2.6 on 2021-10-26 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_tutorprofile_book_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
