# Generated by Django 3.2.6 on 2021-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
