# Generated by Django 3.2.6 on 2021-10-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211026_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='frequency',
            field=models.CharField(choices=[(1, '1 session'), (2, '2 session'), (3, '3 session'), (4, '4 session'), (5, '5 session'), (0, 'Not sure')], default='Not sure', max_length=10),
        ),
    ]
