# Generated by Django 3.2.9 on 2021-11-07 09:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_bookings_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='programming_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Swift', 'Swift'), ('Java', 'Java'), ('Sql', 'Sql'), ('PHP', 'PHP'), ('C#', 'C#')], max_length=39, null=True),
        ),
    ]
