# Generated by Django 3.2.6 on 2021-11-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_bookings_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
