# Generated by Django 3.2.6 on 2021-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_bookings_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
