# Generated by Django 3.2.6 on 2021-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_bookings_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
